dist: bionic
language: python

python:
  - "3.7"

env:
  global:
    - CPLUS_INCLUDE_PATH=/usr/include/gdal
    - C_INCLUDE_PATH=/usr/include/gdal

before_install:
  - sed -i -e '/GDAL==2.4.0/d' requirements.txt
  - sudo apt-get install libgdal-dev python3-rtree
  - echo "GDAL==$(gdal-config --version)" >> requirements.txt

install:
  - pip3 install wheel
  - pip3 install -r requirements.txt

stages:
  - compile
  - pep8check
  - pylintcheck
  - test
  - dockerbuild
  - codecov

jobs:
  include:
    - stage: compile
      script:
        - python3 -m compileall .
    - stage: pep8check
      install:
        - pip3 install pycodestyle
      script:
        - shopt -s globstar && pycodestyle {,**/}*.py
    - stage: pylintcheck
      install:
        - pip3 install -r requirements.txt
        - pip3 install pylint
      script:
        - shopt -s globstar && pylint --exit-zero {,**/}*.py
    - stage: test
      script:
        - python3 test_all.py
    - stage: dockerbuild
      before_install: skip
      install: skip
      script:
        - docker build -f metadata/Dockerfile .
    - stage: codecov
      script:
        - pip3 install coverage codecov
        - coverage run test_all.py
      after_success:
        - codecov -t ${CODECOV_TOKEN}
