dist: bionic
language: python

stages:
  - compile
  - pep8check
  - pylintcheck
  - test

jobs:
  include:
    - stage: compile
      script:
        - python3 -m compileall .
    - stage: pep8check
      install:
        - pip3 install pycodestyle
      script:
        - pycodestyle *.py
    - stage: pylintcheck
      install:
        - pip3 install -r requirements.txt
        - pip3 install pylint
      script:
        - pylint --exit-zero *.py
    - stage: test
      script:
        - python3 test_all.py
